name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discord-feedback-server:${{ github.sha }}
          file: ./Dockerfile

      # Update the configuration repository with the new image tag
      - name: Update Config Repository
        uses: actions/checkout@v4
        with:
          repository: quangtruong452001/discord-feedback-server-config
          ref: main
          ssh-key: ${{ secrets.CONFIG_SSH_TOKEN }}
          path: config-repo

      # Git config setup
      - name: Git Config
        id: config-git
        run: |
          cd config-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "date-build=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      # Kustomize Setup
      - name: Setup kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          chmod u+x ./kustomize
          sudo mv ./kustomize /usr/local/bin/kustomize

        # Update image path
      - name: NON-TAG Update the image
        run: |
          cd config-repo/k8s
          kustomize edit set image ${{ secrets.DOCKER_HUB_USERNAME }}/discord-feedback-server=${{ secrets.DOCKER_HUB_USERNAME }}/discord-feedback-server:${{ github.sha }}

        # Commit and Push changes
      - name: Commit and Push changes
        run: |
          cd config-repo
          git add .
          git commit -m "Update image taf" || echo "No changes to commit"
          git push
